### ISSUE TITLE
Add utility function for fight decisions 

### ISSUE THREAD

**Issue by Razvan00Rusu** [Razvan00Rusu/SOMAS2022-Team6#2]
Work out a way of judging the decisions other agents are making in the fight decision round.

If agents have high hp, they should probably be fighting - punished for not fighting, but also not rewarded much for fighting
Similar for low hp

**Comment by thl19git** [comment]
For this it would probably make sense to first come up with our idea of what each agent should be doing. That is in essence our initial fight proposal. We can then talk to agents and change one or both of our proposal and some measure of the agents bravery etc. Then whenever a proposal is put forward, we can compare it to our own proposal to see what we think of it (can also consider some of the agent measures / scores we are maintaining).
