### ISSUE TITLE
What utility rankings do we want?

### ISSUE THREAD

**Issue by Issa-Bqain** [Razvan00Rusu/SOMAS2022-Team6#5]
What can we base the utility rankings on?
- Manifestos - 
- Fight decisions - what the agent does in the end
- Fight proposals - broadcast by the leader based on proposal of an agent - 
- Trading - No access to this information?
- Inventory - Are they hoarding? 
-

**Comment by thl19git** [comment]
Some basic ideas:
- **Sensibility** (fight contribution)
    - A measure tracking the fight decision making of an agent
    - Updated after each fight round, by comparing stats before the fight and the fight decision
    - Would require us to know if what the agent wanted to do differed from what the leader chose for that agent (if applicable)
    - Can be used when choosing leader or whether to trade with someone (and what to give them)
- **Leadership**
    - A measure tracking how well an agent performs as leader
    - Updated after each fight round and each loot distribution round
    - Used when voting for a new leader and during no confidence votes
- **Trading**
    - A measure tracking how cooperative/fair an agent has been when trading with us
    - Updated after every trade / attempted trade
    - Used when deciding who to trade with, what to trade, and potentially also in leadership elections
